[platformio]
default_envs = t_display_long_smoke
boards_dir = ../../boards

[env:t_display_long_smoke]
platform = espressif32
framework = arduino
board = T-Display-Long
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=3
